Stage19 + EPN fixed

diff --git a/myexpos/expl/expl b/myexpos/expl/expl
--- a/myexpos/expl/expl
+++ b/myexpos/expl/expl
@@ -1,7 +1,13 @@
-yacc -d -v abstree.y
-lex abstree.l
-gcc lex.yy.c y.tab.c -w
-./a.out $1
-lex ltranslate.l
-gcc lex.yy.c
-./a.out
+
+#Compiling
+./expl-bin $1
+if [ $? -eq 1 ]
+then
+echo "compilation failed"
+exit 1
+fi
+
+#Label Translation
+./ltranslate
+
+cp "assemblycode.xsm" "${1%.*}.xsm"
